### ISSUE TITLE
basic.csv has inconsistent newlines

### ISSUE THREAD

**Issue by hildjj** [cabo/edn-abnf#2]
I think there are a couple of lines at the end that have \r\n in them rather than \n.  That is causing me to get different results than you.

**Comment by cabo** [comment]
That is actually intended (tests whether CR is properly ignored)

**Comment by hildjj** [comment]
Please find some other way to test this.  It required several minutes and a hex editor to figure out what was going on, and there's no way to edit this file with a normal editor and retain the formatting.  To fix this, literally all I did was open the file and save it in my normal editor without making any changes.

Also, I still disagree with the test.  The grammar has a comment saying "ignored on input", but there is no normative text explaining this that I could find, and this is such a shocking result of using the ABNF that there would have to be normative text explaining it.

**Comment by cabo** [comment]
On 2024-08-22, at 18:39, Joe Hildebrand ***@***.***> wrote:
> 
> 
> Please find some other way to test this. 

100 % agreement.
As I said, this was a lazy way to get the test in for my tool.
I probably have to do the inverse of the x tests to test details like that.
Let me think about a good way to do this.

> It required several minutes and a hex editor to figure out what was going on, and there's no way to edit this file with a normal editor and retain the formatting. To fix this, literally all I did was open the file and save it in my normal editor without making any changes.
> 
> Also, I still disagree with the test. The grammar has a comment saying "ignored on input", but there is no normative text explaining this that I could find, and this is such a shocking result of using the ABNF that there would have to be normative text explaining it.

ABNF unfortunately is a language for grammars, not for the transformations of sentences that match the grammar.  So that cannot be done formally in the ABNF, and we have long used ABNF comments to provide information like this.

Authors of EDN have no way to control whether you will see a CR on your system’s copy of the EDN or not.  Retaining the CRs that are randomly put in by your system or not would be a major interoperability failure.  Hence they are ignored.
(You can put in explicit ones with \r, which of course are retained by the tstr/sqstr processing.  But this was not what the example was testing.)

Grüße, Carsten

**Comment by hildjj** [comment]
Not disagreeing with you about CR's being ignored.

I'm asking that normative text outside the grammar be added to explain the throw-away comment in the grammar.  This seems like a list discussion, I'll take it there.

**Comment by hildjj** [comment]
Actually, leaving this open because you said you wanted to change the approach you used.  I'll close the PR.

**Comment by cabo** [comment]
On 22. Aug 2024, at 19:30, Joe Hildebrand ***@***.***> wrote:
> 
> 
> Actually, leaving this open because you said you wanted to change the approach you used. I'll close the PR.

Indeed, I’m trying to dream up a way to accept hexdumps of EDN as input everywhere in the test vector CSVs.

I’m currently leaning to adding a prefix like x] that says the rest of the entry is a hexdump of EDN.
(It needs to be something ugly like x] so it doesn’t occur in actual EDN…)
If you have a better prefix, please suggest it...

I’ll also make an issue over in edn-literal to make the fact that CRs are ignore in the input more explicit outside the ABNF, too.

Grüße, Carsten

**Comment by hildjj** [comment]
What about a new op type like 'h' that means that col two is hex(edn)?

I sent proposed text to the list. It's overly-verbose, but captures everything I thought was relevant.

**Comment by cabo** [comment]
On 22. Aug 2024, at 20:14, Joe Hildebrand ***@***.***> wrote:
> 
> I sent proposed text to the list. It's overly-verbose, but captures everything I thought was relevant.
> 

I added more verbosity and will send a PR in a few minutes.

Thanks!

Grüße, Carsten

**Comment by cabo** [comment]
On 22. Aug 2024, at 20:14, Joe Hildebrand ***@***.***> wrote:
> 
> What about a new op type like 'h' that means that col two is hex(edn)?


I just want to be able to use them in column 3 as well.
(We also need to keep the bit saying whether the match is correct or not.)

Any allergies to x]? Maybe h]?

**Comment by hildjj** [comment]
In column 2?  I'm not a big fan.  Op codes are cheap, define one for each combination you actually want to use.

**Comment by cabo** [comment]
It was too easy to do h], I'm afraid...
Not a big fan either, but quite workable.
Probably a cleanup of what opcodes we need with which parameters is next (plus some automatic conversion).

**Comment by hildjj** [comment]
Works for me.
