### ISSUE TITLE
Escaped single-quote in tstr

### ISSUE THREAD

**Issue by hildjj** [cabo/edn-abnf#4]
Are you in the midst of adding support for `"foo\'bar"` to the grammar?  If so, close this.

Other than that, I don't see how this parses?

https://github.com/cabo/edn-abnf/blob/9008f2e10ed40ac6e95bf9a7db4d2e8862ce494f/tests/basic.csv#L46

**Comment by hildjj** [comment]
Never mind, I had a different issue.  Apologies for the noise.

**Comment by cabo** [comment]
I'd say this is another nudge to finally change the quote-char from " to something like |
